'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  Train:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      repo:
        type: volume
    uses: script@v1
    with:
      script: python train.py
      image: pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime
  Predict:
    resources:
      instance-type: C5
    needs:
      - Train
    inputs:
      repo: Train.outputs.repo
    uses: script@v1
    with:
      script: python predict.py
      image: pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime
